### ISSUE TITLE
Writing to SPI SS1306 OLED Display with nanoframework

### ISSUE THREAD

**Issue by noumanqaiser** [Dweaver309/nanoframework.SS1306#2]
Hi Team, 

I was wondering if the commands/data sent to the display would change if the SS1306 display was connected to the esp32 using SPI instead of i2C. What sort of changes could be required to make that happen.

Would appreciate any support.

**Comment by Dweaver309** [comment]
I haven't tried SPI you may want to post a question on the nanoFramework Discord channel.

**Comment by Dweaver309** [comment]
This link may help
https://github.com/WildernessLabs/Netduino.Foundation/blob/main/Source/Peripheral_Libs/Displays.SSD1306/Driver/SSD1306.cs
